package Components;

import Communication.ComData;

/**
 *
 * @author edatabit
 */
public class PSUAlarms extends javax.swing.JPanel {

    /**
     * Creates new form PSUAlarms
     */
    public PSUAlarms() {
        initComponents();
    }

    public void displayPSUAlarms() {
        if(ComData.getTLastPoll(11, 2).equals("0"))
        {  
            jTextField225.setText(ComData.getTPSUAlarm(0, 1));
            jTextField225.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(0, 2)));
            jTextField226.setText(ComData.getTPSUAlarm(2, 1));
            jTextField226.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(2, 2)));
            jTextField227.setText(ComData.getTPSUAlarm(4, 1));
            jTextField227.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(4, 2)));
            jTextField228.setText(ComData.getTPSUAlarm(6, 1));
            jTextField228.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(6, 2)));
            jTextField229.setText(ComData.getTPSUAlarm(8, 1));
            jTextField229.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(8, 2)));
        }
        else
        {  
            jTextField225.setText(ComData.getTPSUAlarm(0, 1));
            jTextField225.setBackground(UX.PColor.setBackGround("-2"));
            jTextField226.setText(ComData.getTPSUAlarm(2, 1));
            jTextField226.setBackground(UX.PColor.setBackGround("-2"));
            jTextField227.setText(ComData.getTPSUAlarm(4, 1));
            jTextField227.setBackground(UX.PColor.setBackGround("-2"));
            jTextField228.setText(ComData.getTPSUAlarm(6, 1));
            jTextField228.setBackground(UX.PColor.setBackGround("-2"));
            jTextField229.setText(ComData.getTPSUAlarm(8, 1));
            jTextField229.setBackground(UX.PColor.setBackGround("-2"));
        }            
        if(ComData.getTLastPoll(12, 2).equals("0"))
        {  
        
            jTextField230.setText(ComData.getTPSUAlarm(1, 1));
            jTextField230.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(1, 2)));
            jTextField231.setText(ComData.getTPSUAlarm(3, 1));
            jTextField231.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(3, 2)));
            jTextField232.setText(ComData.getTPSUAlarm(5, 1));
            jTextField232.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(5, 2)));
            jTextField233.setText(ComData.getTPSUAlarm(7, 1));
            jTextField233.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(7, 2)));
            jTextField234.setText(ComData.getTPSUAlarm(9, 1));
            jTextField234.setBackground(UX.PColor.setBackGround(ComData.getTPSUAlarm(9, 2)));
        }
        else
        {  
        
            jTextField230.setText(ComData.getTPSUAlarm(1, 1));
            jTextField230.setBackground(UX.PColor.setBackGround("-2"));
            jTextField231.setText(ComData.getTPSUAlarm(3, 1));
            jTextField231.setBackground(UX.PColor.setBackGround("-2"));
            jTextField232.setText(ComData.getTPSUAlarm(5, 1));
            jTextField232.setBackground(UX.PColor.setBackGround("-2"));
            jTextField233.setText(ComData.getTPSUAlarm(7, 1));
            jTextField233.setBackground(UX.PColor.setBackGround("-2"));
            jTextField234.setText(ComData.getTPSUAlarm(9, 1));
            jTextField234.setBackground(UX.PColor.setBackGround("-2"));
        }            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel89 = new javax.swing.JPanel();
        jTextField225 = new javax.swing.JTextField();
        jTextField226 = new javax.swing.JTextField();
        jTextField227 = new javax.swing.JTextField();
        jTextField228 = new javax.swing.JTextField();
        jTextField229 = new javax.swing.JTextField();
        jPanel90 = new javax.swing.JPanel();
        jTextField230 = new javax.swing.JTextField();
        jTextField231 = new javax.swing.JTextField();
        jTextField232 = new javax.swing.JTextField();
        jTextField233 = new javax.swing.JTextField();
        jTextField234 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PSU Alarms", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jPanel89.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PSU A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTextField225.setEditable(false);
        jTextField225.setBackground(new java.awt.Color(204, 255, 255));
        jTextField225.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField225.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField225.setText("No Fault?");
        jTextField225.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField225.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField225.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField226.setEditable(false);
        jTextField226.setBackground(new java.awt.Color(204, 255, 255));
        jTextField226.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField226.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField226.setText("No Fault?");
        jTextField226.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField226.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField226.setName(""); // NOI18N
        jTextField226.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField227.setEditable(false);
        jTextField227.setBackground(new java.awt.Color(204, 255, 255));
        jTextField227.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField227.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField227.setText("No Fault?");
        jTextField227.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField227.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField227.setName(""); // NOI18N
        jTextField227.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField228.setEditable(false);
        jTextField228.setBackground(new java.awt.Color(204, 255, 255));
        jTextField228.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField228.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField228.setText("No Fault?");
        jTextField228.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField228.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField228.setName(""); // NOI18N
        jTextField228.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField229.setEditable(false);
        jTextField229.setBackground(new java.awt.Color(204, 255, 255));
        jTextField229.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField229.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField229.setText("No Fault?");
        jTextField229.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField229.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField229.setName(""); // NOI18N
        jTextField229.setPreferredSize(new java.awt.Dimension(80, 30));

        javax.swing.GroupLayout jPanel89Layout = new javax.swing.GroupLayout(jPanel89);
        jPanel89.setLayout(jPanel89Layout);
        jPanel89Layout.setHorizontalGroup(
            jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField225, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(jTextField226, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField227, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField228, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField229, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel89Layout.setVerticalGroup(
            jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel89Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField225, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField226, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField227, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField228, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField229, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel90.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PSU B", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTextField230.setEditable(false);
        jTextField230.setBackground(new java.awt.Color(204, 255, 255));
        jTextField230.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField230.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField230.setText("No Fault?");
        jTextField230.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField230.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField230.setName(""); // NOI18N
        jTextField230.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField231.setEditable(false);
        jTextField231.setBackground(new java.awt.Color(204, 255, 255));
        jTextField231.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField231.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField231.setText("No Fault?");
        jTextField231.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField231.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField231.setName(""); // NOI18N
        jTextField231.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField232.setEditable(false);
        jTextField232.setBackground(new java.awt.Color(204, 255, 255));
        jTextField232.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField232.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField232.setText("No Fault?");
        jTextField232.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField232.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField232.setName(""); // NOI18N
        jTextField232.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField233.setEditable(false);
        jTextField233.setBackground(new java.awt.Color(204, 255, 255));
        jTextField233.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField233.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField233.setText("No Fault?");
        jTextField233.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField233.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField233.setName(""); // NOI18N
        jTextField233.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField234.setEditable(false);
        jTextField234.setBackground(new java.awt.Color(204, 255, 255));
        jTextField234.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField234.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField234.setText("No Fault?");
        jTextField234.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField234.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField234.setName(""); // NOI18N
        jTextField234.setPreferredSize(new java.awt.Dimension(80, 30));

        javax.swing.GroupLayout jPanel90Layout = new javax.swing.GroupLayout(jPanel90);
        jPanel90.setLayout(jPanel90Layout);
        jPanel90Layout.setHorizontalGroup(
            jPanel90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField230, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
            .addComponent(jTextField231, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField232, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField233, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField234, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel90Layout.setVerticalGroup(
            jPanel90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel90Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField230, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField231, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField232, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField233, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField234, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel89;
    private javax.swing.JPanel jPanel90;
    private javax.swing.JTextField jTextField225;
    private javax.swing.JTextField jTextField226;
    private javax.swing.JTextField jTextField227;
    private javax.swing.JTextField jTextField228;
    private javax.swing.JTextField jTextField229;
    private javax.swing.JTextField jTextField230;
    private javax.swing.JTextField jTextField231;
    private javax.swing.JTextField jTextField232;
    private javax.swing.JTextField jTextField233;
    private javax.swing.JTextField jTextField234;
    // End of variables declaration//GEN-END:variables
}
