package Components;

import Communication.ComData;

/**
 *
 * @author edatabit
 */
public class RCUAlarms extends javax.swing.JPanel {

    /**
     * Creates new form RCUAlarms
     */
    public RCUAlarms() {
        initComponents();
    }

    private String mergeAlarms(String primary, String secondary) {
        if (!primary.equals("0")) {
            return primary;
        } else {
            return secondary;
        }
    }

    public void displayRCUAlarms() {
        if(ComData.getTLastPoll(1, 2).equals("0"))
        {  
            jTextField207.setText(ComData.getTRCUAlarm(0, 1));
            jTextField207.setBackground(UX.PColor.setBackGround(ComData.getTRCUAlarm(0, 2)));
            jTextField208.setText(ComData.getTRCUAlarm(1, 1));
            jTextField208.setBackground(UX.PColor.setBackGround(ComData.getTRCUAlarm(1, 2)));
            jTextField209.setText(ComData.getTRCUAlarm(2, 1));
            jTextField209.setBackground(UX.PColor.setBackGround(ComData.getTRCUAlarm(2, 2)));
            jTextField210.setText(ComData.getTRCUAlarm(3, 1));
            jTextField210.setBackground(UX.PColor.setBackGround(ComData.getTRCUAlarm(3, 2)));
            jTextField211.setText(ComData.getTRCUAlarm(4, 1));
            jTextField211.setBackground(UX.PColor.setBackGround(ComData.getTRCUAlarm(4, 2)));

            jTextField217.setText(ComData.getTRCUAlarm(5, 1));
            jTextField217.setBackground(UX.PColor.setBackGround(mergeAlarms(ComData.getTRCUAlarm(5, 2), ComData.getTRCUAlarm(6, 2))));
            jTextField219.setText(ComData.getTRCUAlarm(7, 1));
            jTextField219.setBackground(UX.PColor.setBackGround(mergeAlarms(ComData.getTRCUAlarm(7, 2), ComData.getTRCUAlarm(8, 2))));
        }
        else
        {  
            jTextField207.setText(ComData.getTRCUAlarm(0, 1));
            jTextField207.setBackground(UX.PColor.setBackGround("-2"));
            jTextField208.setText(ComData.getTRCUAlarm(1, 1));
            jTextField208.setBackground(UX.PColor.setBackGround("-2"));
            jTextField209.setText(ComData.getTRCUAlarm(2, 1));
            jTextField209.setBackground(UX.PColor.setBackGround("-2"));
            jTextField210.setText(ComData.getTRCUAlarm(3, 1));
            jTextField210.setBackground(UX.PColor.setBackGround("-2"));
            jTextField211.setText(ComData.getTRCUAlarm(4, 1));
            jTextField211.setBackground(UX.PColor.setBackGround("-2"));

            jTextField217.setText(ComData.getTRCUAlarm(5, 1));
            jTextField217.setBackground(UX.PColor.setBackGround("-2"));
            jTextField219.setText(ComData.getTRCUAlarm(7, 1));
            jTextField219.setBackground(UX.PColor.setBackGround("-2"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel83 = new javax.swing.JPanel();
        jTextField207 = new javax.swing.JTextField();
        jTextField208 = new javax.swing.JTextField();
        jTextField209 = new javax.swing.JTextField();
        jTextField210 = new javax.swing.JTextField();
        jTextField211 = new javax.swing.JTextField();
        jPanel86 = new javax.swing.JPanel();
        jTextField217 = new javax.swing.JTextField();
        jTextField219 = new javax.swing.JTextField();

        jPanel83.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RCU Alarms", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jTextField207.setEditable(false);
        jTextField207.setBackground(new java.awt.Color(204, 255, 255));
        jTextField207.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField207.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField207.setText("No Fault?");
        jTextField207.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField207.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField207.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField208.setEditable(false);
        jTextField208.setBackground(new java.awt.Color(204, 255, 255));
        jTextField208.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField208.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField208.setText("No Fault?");
        jTextField208.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField208.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField208.setName(""); // NOI18N
        jTextField208.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField209.setEditable(false);
        jTextField209.setBackground(new java.awt.Color(204, 255, 255));
        jTextField209.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField209.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField209.setText("No Fault?");
        jTextField209.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField209.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField209.setName(""); // NOI18N
        jTextField209.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField210.setEditable(false);
        jTextField210.setBackground(new java.awt.Color(204, 255, 255));
        jTextField210.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField210.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField210.setText("No Fault?");
        jTextField210.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField210.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField210.setName(""); // NOI18N
        jTextField210.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField211.setEditable(false);
        jTextField211.setBackground(new java.awt.Color(204, 255, 255));
        jTextField211.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField211.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField211.setText("No Fault?");
        jTextField211.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField211.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField211.setName(""); // NOI18N
        jTextField211.setPreferredSize(new java.awt.Dimension(80, 30));

        javax.swing.GroupLayout jPanel83Layout = new javax.swing.GroupLayout(jPanel83);
        jPanel83.setLayout(jPanel83Layout);
        jPanel83Layout.setHorizontalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField207, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addComponent(jTextField208, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField209, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField210, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField211, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel83Layout.setVerticalGroup(
            jPanel83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel83Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField207, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField208, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField209, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField211, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel86.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RCU Alarms - TXP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jTextField217.setEditable(false);
        jTextField217.setBackground(new java.awt.Color(204, 255, 255));
        jTextField217.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField217.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField217.setText("No Fault?");
        jTextField217.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField217.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField217.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField219.setEditable(false);
        jTextField219.setBackground(new java.awt.Color(204, 255, 255));
        jTextField219.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField219.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField219.setText("No Fault?");
        jTextField219.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField219.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField219.setName(""); // NOI18N
        jTextField219.setPreferredSize(new java.awt.Dimension(80, 30));

        javax.swing.GroupLayout jPanel86Layout = new javax.swing.GroupLayout(jPanel86);
        jPanel86.setLayout(jPanel86Layout);
        jPanel86Layout.setHorizontalGroup(
            jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField217, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addComponent(jTextField219, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel86Layout.setVerticalGroup(
            jPanel86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel86Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField217, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField219, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel86;
    private javax.swing.JTextField jTextField207;
    private javax.swing.JTextField jTextField208;
    private javax.swing.JTextField jTextField209;
    private javax.swing.JTextField jTextField210;
    private javax.swing.JTextField jTextField211;
    private javax.swing.JTextField jTextField217;
    private javax.swing.JTextField jTextField219;
    // End of variables declaration//GEN-END:variables
}
