package Components;

import Communication.ComData;

/**
 *
 * @author edatabit
 */
public class RXUStatusAlarms extends javax.swing.JPanel {

    /**
     * Creates new form RXUStatusAlarms
     */
    public RXUStatusAlarms() {
        initComponents();
    }

    public void displayRXUAlarms() {
        if(ComData.getTLastPoll(9, 2).equals("0"))
        {  
            jTextField195.setText(ComData.getTRXUAlarm(0, 1));
            jTextField195.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(0, 2)));
            jTextField196.setText(ComData.getTRXUAlarm(2, 1));
            jTextField196.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(2, 2)));
            jTextField197.setText(ComData.getTRXUAlarm(4, 1));
            jTextField197.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(4, 2)));
            jTextField198.setText(ComData.getTRXUAlarm(6, 1));
            jTextField198.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(6, 2)));
            jTextField199.setText(ComData.getTRXUAlarm(8, 1));
            jTextField199.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(8, 2)));
            jTextField200.setText(ComData.getTRXUAlarm(10, 1));
            jTextField200.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(10, 2)));    
        }
        else
        {  
            jTextField195.setText(ComData.getTRXUAlarm(0, 1));
            jTextField195.setBackground(UX.PColor.setBackGround("-2"));
            jTextField196.setText(ComData.getTRXUAlarm(2, 1));
            jTextField196.setBackground(UX.PColor.setBackGround("-2"));
            jTextField197.setText(ComData.getTRXUAlarm(4, 1));
            jTextField197.setBackground(UX.PColor.setBackGround("-2"));
            jTextField198.setText(ComData.getTRXUAlarm(6, 1));
            jTextField198.setBackground(UX.PColor.setBackGround("-2"));
            jTextField199.setText(ComData.getTRXUAlarm(8, 1));
            jTextField199.setBackground(UX.PColor.setBackGround("-2"));
            jTextField200.setText(ComData.getTRXUAlarm(10, 1));
            jTextField200.setBackground(UX.PColor.setBackGround("-2"));
        }            
        if(ComData.getTLastPoll(10, 2).equals("0"))
            {        
            jTextField201.setText(ComData.getTRXUAlarm(1, 1));
            jTextField201.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(1, 2)));
            jTextField202.setText(ComData.getTRXUAlarm(3, 1));
            jTextField202.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(3, 2)));
            jTextField203.setText(ComData.getTRXUAlarm(5, 1));
            jTextField203.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(5, 2)));
            jTextField204.setText(ComData.getTRXUAlarm(7, 1));
            jTextField204.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(7, 2)));
            jTextField205.setText(ComData.getTRXUAlarm(9, 1));
            jTextField205.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(9, 2)));
            jTextField206.setText(ComData.getTRXUAlarm(11, 1));
            jTextField206.setBackground(UX.PColor.setBackGround(ComData.getTRXUAlarm(11, 2)));
        }
        else
        {        
            jTextField201.setText(ComData.getTRXUAlarm(1, 1));
            jTextField201.setBackground(UX.PColor.setBackGround("-2"));
            jTextField202.setText(ComData.getTRXUAlarm(3, 1));
            jTextField202.setBackground(UX.PColor.setBackGround("-2"));
            jTextField203.setText(ComData.getTRXUAlarm(5, 1));
            jTextField203.setBackground(UX.PColor.setBackGround("-2"));
            jTextField204.setText(ComData.getTRXUAlarm(7, 1));
            jTextField204.setBackground(UX.PColor.setBackGround("-2"));
            jTextField205.setText(ComData.getTRXUAlarm(9, 1));
            jTextField205.setBackground(UX.PColor.setBackGround("-2"));
            jTextField206.setText(ComData.getTRXUAlarm(11, 1));
            jTextField206.setBackground(UX.PColor.setBackGround("-2"));
        }           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel80 = new javax.swing.JPanel();
        jTextField195 = new javax.swing.JTextField();
        jTextField196 = new javax.swing.JTextField();
        jTextField197 = new javax.swing.JTextField();
        jTextField198 = new javax.swing.JTextField();
        jTextField199 = new javax.swing.JTextField();
        jTextField200 = new javax.swing.JTextField();
        jPanel81 = new javax.swing.JPanel();
        jTextField201 = new javax.swing.JTextField();
        jTextField202 = new javax.swing.JTextField();
        jTextField203 = new javax.swing.JTextField();
        jTextField204 = new javax.swing.JTextField();
        jTextField205 = new javax.swing.JTextField();
        jTextField206 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RXUStatusAlarms", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        setMaximumSize(new java.awt.Dimension(338, 280));
        setMinimumSize(new java.awt.Dimension(338, 280));

        jPanel80.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RXU A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel80.setPreferredSize(new java.awt.Dimension(155, 255));

        jTextField195.setEditable(false);
        jTextField195.setBackground(new java.awt.Color(204, 255, 255));
        jTextField195.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField195.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField195.setText("No Fault?");
        jTextField195.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField195.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField195.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField196.setEditable(false);
        jTextField196.setBackground(new java.awt.Color(204, 255, 255));
        jTextField196.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField196.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField196.setText("No Fault?");
        jTextField196.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField196.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField196.setName(""); // NOI18N
        jTextField196.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField197.setEditable(false);
        jTextField197.setBackground(new java.awt.Color(204, 255, 255));
        jTextField197.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField197.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField197.setText("No Fault?");
        jTextField197.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField197.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField197.setName(""); // NOI18N
        jTextField197.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField198.setEditable(false);
        jTextField198.setBackground(new java.awt.Color(204, 255, 255));
        jTextField198.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField198.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField198.setText("No Fault?");
        jTextField198.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField198.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField198.setName(""); // NOI18N
        jTextField198.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField199.setEditable(false);
        jTextField199.setBackground(new java.awt.Color(204, 255, 255));
        jTextField199.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField199.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField199.setText("No Fault?");
        jTextField199.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField199.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField199.setName(""); // NOI18N
        jTextField199.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField200.setEditable(false);
        jTextField200.setBackground(new java.awt.Color(204, 255, 255));
        jTextField200.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField200.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField200.setText("No Fault?");
        jTextField200.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField200.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField200.setName(""); // NOI18N
        jTextField200.setPreferredSize(new java.awt.Dimension(80, 30));

        javax.swing.GroupLayout jPanel80Layout = new javax.swing.GroupLayout(jPanel80);
        jPanel80.setLayout(jPanel80Layout);
        jPanel80Layout.setHorizontalGroup(
            jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField195, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(jTextField196, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField197, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField198, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField199, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel80Layout.setVerticalGroup(
            jPanel80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel80Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField195, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField196, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField197, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField198, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField199, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel81.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RXU B", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel81.setPreferredSize(new java.awt.Dimension(155, 255));

        jTextField201.setEditable(false);
        jTextField201.setBackground(new java.awt.Color(204, 255, 255));
        jTextField201.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField201.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField201.setText("No Fault?");
        jTextField201.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField201.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField201.setName(""); // NOI18N
        jTextField201.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField202.setEditable(false);
        jTextField202.setBackground(new java.awt.Color(204, 255, 255));
        jTextField202.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField202.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField202.setText("No Fault?");
        jTextField202.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField202.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField202.setName(""); // NOI18N
        jTextField202.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField203.setEditable(false);
        jTextField203.setBackground(new java.awt.Color(204, 255, 255));
        jTextField203.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField203.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField203.setText("No Fault?");
        jTextField203.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField203.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField203.setName(""); // NOI18N
        jTextField203.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField204.setEditable(false);
        jTextField204.setBackground(new java.awt.Color(204, 255, 255));
        jTextField204.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField204.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField204.setText("No Fault?");
        jTextField204.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField204.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField204.setName(""); // NOI18N
        jTextField204.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField205.setEditable(false);
        jTextField205.setBackground(new java.awt.Color(204, 255, 255));
        jTextField205.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField205.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField205.setText("No Fault?");
        jTextField205.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField205.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField205.setName(""); // NOI18N
        jTextField205.setPreferredSize(new java.awt.Dimension(80, 30));

        jTextField206.setEditable(false);
        jTextField206.setBackground(new java.awt.Color(204, 255, 255));
        jTextField206.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField206.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField206.setText("No Fault?");
        jTextField206.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField206.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField206.setName(""); // NOI18N
        jTextField206.setPreferredSize(new java.awt.Dimension(80, 30));

        javax.swing.GroupLayout jPanel81Layout = new javax.swing.GroupLayout(jPanel81);
        jPanel81.setLayout(jPanel81Layout);
        jPanel81Layout.setHorizontalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField201, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(jTextField202, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField203, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField204, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField205, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField206, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel81Layout.setVerticalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel81Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField202, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField203, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField204, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField205, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField206, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JTextField jTextField195;
    private javax.swing.JTextField jTextField196;
    private javax.swing.JTextField jTextField197;
    private javax.swing.JTextField jTextField198;
    private javax.swing.JTextField jTextField199;
    private javax.swing.JTextField jTextField200;
    private javax.swing.JTextField jTextField201;
    private javax.swing.JTextField jTextField202;
    private javax.swing.JTextField jTextField203;
    private javax.swing.JTextField jTextField204;
    private javax.swing.JTextField jTextField205;
    private javax.swing.JTextField jTextField206;
    // End of variables declaration//GEN-END:variables
}
