package Windows;

import Configuration.Config;
import java.awt.Color;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableModel;

/**
 *
 * @author edatabit
 */
public class Settings extends javax.swing.JDialog {

    private int index = -1;

    public Settings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        StationsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        StationsTable.setSelectionBackground(Color.RED);
        StationsTable.setSelectionForeground(Color.YELLOW);
        StationsTable.setDefaultEditor(Object.class, null);
        DelRow.setEnabled(false);
        EditRow.setEnabled(false);
        loadData();
    }

    private static void loadData() {

        String[] cols = {"Name", "IP Address", "Port for SNMP", "User", "Password", "Port for WEB"};
        String[][] model = Config.Stations;
        StationsTable.setModel(new javax.swing.table.DefaultTableModel(model, cols));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        SaveAll = new javax.swing.JButton();
        CancelAll = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AddRow = new javax.swing.JButton();
        EditRow = new javax.swing.JButton();
        DelRow = new javax.swing.JButton();
        FieldName = new javax.swing.JTextField();
        FieldIP = new javax.swing.JTextField();
        FieldPort = new javax.swing.JTextField();
        FieldUser = new javax.swing.JTextField();
        FieldPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FieldWPort = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StationsTable = new javax.swing.JTable();
        MessageWindow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setMinimumSize(new java.awt.Dimension(761, 487));

        SaveAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/16/dropboxstatus-busy2.png"))); // NOI18N
        SaveAll.setText("Save");
        SaveAll.setMaximumSize(new java.awt.Dimension(90, 30));
        SaveAll.setMinimumSize(new java.awt.Dimension(90, 30));
        SaveAll.setPreferredSize(new java.awt.Dimension(90, 30));
        SaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAllActionPerformed(evt);
            }
        });

        CancelAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/16/application-exit.png"))); // NOI18N
        CancelAll.setText("Cancel");
        CancelAll.setMaximumSize(new java.awt.Dimension(100, 30));
        CancelAll.setMinimumSize(new java.awt.Dimension(100, 30));
        CancelAll.setPreferredSize(new java.awt.Dimension(100, 30));
        CancelAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CancelAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(SaveAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add / Edit / Delete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        AddRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/16/list-add.png"))); // NOI18N
        AddRow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AddRow.setLabel("Add");
        AddRow.setMaximumSize(new java.awt.Dimension(120, 25));
        AddRow.setMinimumSize(new java.awt.Dimension(120, 25));
        AddRow.setPreferredSize(new java.awt.Dimension(120, 25));
        AddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRowActionPerformed(evt);
            }
        });

        EditRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/16/accessories-text-editor.png"))); // NOI18N
        EditRow.setText("Save Edit");
        EditRow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EditRow.setMaximumSize(new java.awt.Dimension(120, 25));
        EditRow.setMinimumSize(new java.awt.Dimension(120, 25));
        EditRow.setPreferredSize(new java.awt.Dimension(120, 25));
        EditRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditRowActionPerformed(evt);
            }
        });

        DelRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/16/list-remove.png"))); // NOI18N
        DelRow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DelRow.setLabel("Delete");
        DelRow.setMaximumSize(new java.awt.Dimension(120, 25));
        DelRow.setMinimumSize(new java.awt.Dimension(120, 25));
        DelRow.setPreferredSize(new java.awt.Dimension(120, 25));
        DelRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelRowActionPerformed(evt);
            }
        });

        FieldName.setBackground(new java.awt.Color(240, 240, 240));
        FieldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldName.setMaximumSize(new java.awt.Dimension(140, 25));
        FieldName.setMinimumSize(new java.awt.Dimension(140, 25));
        FieldName.setPreferredSize(new java.awt.Dimension(140, 25));

        FieldIP.setBackground(new java.awt.Color(240, 240, 240));
        FieldIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldIP.setMaximumSize(new java.awt.Dimension(140, 25));
        FieldIP.setMinimumSize(new java.awt.Dimension(140, 25));
        FieldIP.setPreferredSize(new java.awt.Dimension(140, 25));

        FieldPort.setBackground(new java.awt.Color(240, 240, 240));
        FieldPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldPort.setMaximumSize(new java.awt.Dimension(140, 25));
        FieldPort.setMinimumSize(new java.awt.Dimension(140, 25));
        FieldPort.setPreferredSize(new java.awt.Dimension(140, 25));

        FieldUser.setBackground(new java.awt.Color(240, 240, 240));
        FieldUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldUser.setMaximumSize(new java.awt.Dimension(140, 25));
        FieldUser.setMinimumSize(new java.awt.Dimension(140, 25));
        FieldUser.setPreferredSize(new java.awt.Dimension(140, 25));

        FieldPass.setBackground(new java.awt.Color(240, 240, 240));
        FieldPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldPass.setMaximumSize(new java.awt.Dimension(140, 25));
        FieldPass.setMinimumSize(new java.awt.Dimension(140, 25));
        FieldPass.setPreferredSize(new java.awt.Dimension(140, 25));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name (description):");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("IP Address:");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Port for SNMP:");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User:");
        jLabel4.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(110, 25));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Password:");
        jLabel5.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(110, 25));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Port for WEB:");
        jLabel6.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(110, 25));

        FieldWPort.setBackground(new java.awt.Color(240, 240, 240));
        FieldWPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldWPort.setMaximumSize(new java.awt.Dimension(140, 25));
        FieldWPort.setMinimumSize(new java.awt.Dimension(140, 25));
        FieldWPort.setPreferredSize(new java.awt.Dimension(140, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel7.setText("See help...");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FieldIP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(FieldWPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DelRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FieldWPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(FieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(AddRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DelRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        StationsTable.setBackground(new java.awt.Color(230, 230, 230));
        StationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "IP Adress", "Port", "User", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StationsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        StationsTable.setGridColor(new java.awt.Color(204, 204, 204));
        StationsTable.setRowHeight(24);
        StationsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StationsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StationsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1389, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Stations", new javax.swing.ImageIcon(getClass().getResource("/pic/32/ghex.png")), jPanel4); // NOI18N

        MessageWindow.setBackground(new java.awt.Color(51, 51, 51));
        MessageWindow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MessageWindow.setForeground(new java.awt.Color(255, 255, 0));
        MessageWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MessageWindow.setToolTipText("");
        MessageWindow.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MessageWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MessageWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAllActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelAllActionPerformed

    private void SaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAllActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) StationsTable.getModel();
        Config.WriteStations(dtm);
        this.dispose();
    }//GEN-LAST:event_SaveAllActionPerformed

    private void AddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRowActionPerformed
        int ind = 0;
        int tst = 0;
        String s = FieldName.getText();
        if (!s.equals("")) {
            ind++;
            FieldName.setBackground(new Color(240, 240, 240));
            FieldName.setForeground(new Color(0, 0, 0));
        } else {
            FieldName.setBackground(Color.red);
            FieldName.setForeground(Color.yellow);
        }
        s = FieldIP.getText();
        if (!s.equals("")) {
            ind++;
            FieldIP.setBackground(new Color(240, 240, 240));
            FieldIP.setForeground(new Color(0, 0, 0));
        } else {
            FieldIP.setBackground(Color.red);
            FieldIP.setForeground(Color.yellow);
        }
        s = FieldPort.getText();
        if (!s.equals("")) {
            ind++;
            FieldPort.setBackground(new Color(240, 240, 240));
            FieldPort.setForeground(new Color(0, 0, 0));
        } else {
            FieldPort.setBackground(Color.red);
            FieldPort.setForeground(Color.yellow);
        }
        try {
            tst = Integer.parseInt(s);
        } catch (NumberFormatException e) {
            ind--;
            FieldPort.setBackground(Color.red);
            FieldPort.setForeground(Color.yellow);
        }
        s = FieldUser.getText();
        if (!s.equals("")) {
            ind++;
            FieldUser.setBackground(new Color(240, 240, 240));
            FieldUser.setForeground(new Color(0, 0, 0));
        } else {
            FieldUser.setBackground(Color.red);
            FieldUser.setForeground(Color.yellow);
        }
        s = FieldPass.getText();
        if (!s.equals("")) {
            ind++;
            FieldPass.setBackground(new Color(240, 240, 240));
            FieldPass.setForeground(new Color(0, 0, 0));
        } else {
            FieldPass.setBackground(Color.red);
            FieldPass.setForeground(Color.yellow);
        }
        s = FieldWPort.getText();
        if (!s.equals("")) {
            ind++;
            FieldWPort.setBackground(new Color(240, 240, 240));
            FieldWPort.setForeground(new Color(0, 0, 0));
        } else {
            FieldWPort.setBackground(Color.red);
            FieldWPort.setForeground(Color.yellow);
        }
        try {
            tst = Integer.parseInt(s);
        } catch (NumberFormatException e) {
            ind--;
            FieldWPort.setBackground(Color.red);
            FieldWPort.setForeground(Color.yellow);
        }

        if (ind == 6) {
            DefaultTableModel Model = (DefaultTableModel) StationsTable.getModel();
            Model.addRow(new String[]{FieldName.getText(), FieldIP.getText(), FieldPort.getText(), FieldUser.getText(), FieldPass.getText(), FieldWPort.getText()});
        }

    }//GEN-LAST:event_AddRowActionPerformed

    private void StationsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StationsTableMouseClicked
        index = StationsTable.getSelectedRow();
        DefaultTableModel Model = (DefaultTableModel) StationsTable.getModel();
        FieldName.setText(Model.getValueAt(index, 0).toString());
        FieldIP.setText(Model.getValueAt(index, 1).toString());
        FieldPort.setText(Model.getValueAt(index, 2).toString());
        FieldUser.setText(Model.getValueAt(index, 3).toString());
        FieldPass.setText(Model.getValueAt(index, 4).toString());
        FieldWPort.setText(Model.getValueAt(index, 5).toString());
        DelRow.setEnabled(true);
        EditRow.setEnabled(true);
    }//GEN-LAST:event_StationsTableMouseClicked

    private void EditRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRowActionPerformed
        if (index >= 0) {
            DefaultTableModel Model = (DefaultTableModel) StationsTable.getModel();
            Model.setValueAt(FieldName.getText(), index, 0);
            Model.setValueAt(FieldIP.getText(), index, 1);
            Model.setValueAt(FieldPort.getText(), index, 2);
            Model.setValueAt(FieldUser.getText(), index, 3);
            Model.setValueAt(FieldPass.getText(), index, 4);
            Model.setValueAt(FieldWPort.getText(), index, 5);
            clearEditField();
        }
    }//GEN-LAST:event_EditRowActionPerformed

    private void DelRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelRowActionPerformed
        if (index >= 0) {
            DefaultTableModel Model = (DefaultTableModel) StationsTable.getModel();
            Model.removeRow(index);

            clearEditField();
        }
    }//GEN-LAST:event_DelRowActionPerformed

    private void clearEditField() {
        index = -1;
        EditRow.setEnabled(false);
        DelRow.setEnabled(false);

        FieldName.setText("");
        FieldIP.setText("");
        FieldPort.setText("");
        FieldUser.setText("");
        FieldPass.setText("");
        FieldWPort.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Settings dialog = new Settings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRow;
    private javax.swing.JButton CancelAll;
    private javax.swing.JButton DelRow;
    private javax.swing.JButton EditRow;
    private javax.swing.JTextField FieldIP;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldPass;
    private javax.swing.JTextField FieldPort;
    private javax.swing.JTextField FieldUser;
    private javax.swing.JTextField FieldWPort;
    public javax.swing.JLabel MessageWindow;
    private javax.swing.JButton SaveAll;
    private static javax.swing.JTable StationsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
